name: Build Docs

on:
  workflow_call:
    inputs:
      log-failure-level:
        description: "Antora log failure level (fatal, error, warn)"
        required: false
        type: string
        default: "fatal"
      antora-playbook:
        description: "Path to the Antora playbook file."
        required: false
        type: string
        default: "docs/antora-playbook.yml"
      node-version:
        description: "Node.js version to use for Antora."
        required: false
        type: string
        default: "24"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-node@v7
        with:
          node-version: ${{ inputs.node-version }}

      - uses: $/.github/actions/build-antora-site
        with:
          playbook: ${{ inputs.antora-playbook }}
          log-failure-level: ${{ inputs.log-failure-level }}
