name: Lint (TypeScript)

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use."
        required: false
        type: string
        default: "24"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ inputs.node-version }}

      - run: npm ci

      - run: npm run lint

      - name: Check formatting
        run: npm run format --if-present
